import type { ThemeConfig } from '../core/types'

export const lightTheme: ThemeConfig = {
  name: 'light',
  code: 'github-light',
  colors: {
    text: '#1a1a1a',
    textMuted: '#6b7280',
    background: '#ffffff',
    backgroundSecondary: '#f9fafb',
    border: '#e5e7eb',
    link: '#2563eb',
    linkHover: '#1d4ed8',
    codeBackground: '#f3f4f6',
    codeText: '#1f2937',
    blockquoteBorder: '#d1d5db',
    blockquoteBackground: '#f9fafb',
    tableHeaderBackground: '#f3f4f6',
    tableRowHover: '#f9fafb',
    headingAnchor: '#9ca3af',
  },
}

export const lightGreenTheme: ThemeConfig = {
  name: 'light-green',
  code: 'vitesse-light',
  colors: {
    text: '#14532d',
    textMuted: '#4b7a5a',
    background: '#ffffff',
    backgroundSecondary: '#dcfce7',
    border: '#bbf7d0',
    link: '#16a34a',
    linkHover: '#15803d',
    codeBackground: '#dcfce7',
    codeText: '#14532d',
    blockquoteBorder: '#4ade80',
    blockquoteBackground: '#f0fdf4',
    tableHeaderBackground: '#dcfce7',
    tableRowHover: '#f0fdf4',
    headingAnchor: '#86efac',
  },
}

export const lightOrangeTheme: ThemeConfig = {
  name: 'light-orange',
  code: 'catppuccin-latte',
  colors: {
    text: '#7c2d12',
    textMuted: '#a07040',
    background: '#ffffff',
    backgroundSecondary: '#ffedd5',
    border: '#fed7aa',
    link: '#ea580c',
    linkHover: '#c2410c',
    codeBackground: '#ffedd5',
    codeText: '#7c2d12',
    blockquoteBorder: '#fb923c',
    blockquoteBackground: '#fff7ed',
    tableHeaderBackground: '#ffedd5',
    tableRowHover: '#fff7ed',
    headingAnchor: '#fdba74',
  },
}

export const lightPinkTheme: ThemeConfig = {
  name: 'light-pink',
  code: 'catppuccin-latte',
  colors: {
    text: '#881337',
    textMuted: '#9d4f72',
    background: '#ffffff',
    backgroundSecondary: '#ffe4e6',
    border: '#fecdd3',
    link: '#e11d48',
    linkHover: '#be123c',
    codeBackground: '#ffe4e6',
    codeText: '#881337',
    blockquoteBorder: '#fb7185',
    blockquoteBackground: '#fff1f2',
    tableHeaderBackground: '#ffe4e6',
    tableRowHover: '#fff1f2',
    headingAnchor: '#fda4af',
  },
}

export const lightPurpleTheme: ThemeConfig = {
  name: 'light-purple',
  code: 'vitesse-light',
  colors: {
    text: '#3b0764',
    textMuted: '#7e5baa',
    background: '#ffffff',
    backgroundSecondary: '#f3e8ff',
    border: '#e9d5ff',
    link: '#9333ea',
    linkHover: '#7e22ce',
    codeBackground: '#f3e8ff',
    codeText: '#3b0764',
    blockquoteBorder: '#c084fc',
    blockquoteBackground: '#faf5ff',
    tableHeaderBackground: '#f3e8ff',
    tableRowHover: '#faf5ff',
    headingAnchor: '#d8b4fe',
  },
}

export const darkTheme: ThemeConfig = {
  name: 'dark',
  code: 'one-dark-pro',
  colors: {
    text: '#e6edf3',
    textMuted: '#9da7b3',
    background: '#0d1117',
    backgroundSecondary: '#161b22',
    border: '#30363d',
    link: '#58a6ff',
    linkHover: '#79c0ff',
    codeBackground: '#010409',
    codeText: '#e6edf3',
    blockquoteBorder: '#58a6ff',
    blockquoteBackground: '#161b22',
    tableHeaderBackground: '#161b22',
    tableRowHover: '#1c2128',
    headingAnchor: '#8b949e',
  },
}

export const darkGreenTheme: ThemeConfig = {
  name: 'dark-green',
  code: 'vitesse-dark',
  colors: {
    text: '#e6f4ea',
    textMuted: '#8fbf9f',
    background: '#0b1410',
    backgroundSecondary: '#12201a',
    border: '#1f3a2d',
    link: '#4ade80',
    linkHover: '#86efac',
    codeBackground: '#050b08',
    codeText: '#d1fae5',
    blockquoteBorder: '#22c55e',
    blockquoteBackground: '#12201a',
    tableHeaderBackground: '#14261d',
    tableRowHover: '#1a2f25',
    headingAnchor: '#4ade80',
  },
}

export const darkOrangeTheme: ThemeConfig = {
  name: 'dark-orange',
  code: 'one-dark-pro',
  colors: {
    text: '#fff4e6',
    textMuted: '#d4a373',
    background: '#140f0a',
    backgroundSecondary: '#1f160f',
    border: '#3b2a1a',
    link: '#fb923c',
    linkHover: '#fdba74',
    codeBackground: '#0c0704',
    codeText: '#fff4e6',
    blockquoteBorder: '#f97316',
    blockquoteBackground: '#1f160f',
    tableHeaderBackground: '#24180f',
    tableRowHover: '#2e2014',
    headingAnchor: '#fb923c',
  },
}

export const darkPinkTheme: ThemeConfig = {
  name: 'dark-pink',
  code: 'catppuccin-mocha',
  colors: {
    text: '#fce7f3',
    textMuted: '#b9839c',
    background: '#140c11',
    backgroundSecondary: '#1d1218',
    border: '#3a1f2d',
    link: '#f472b6',
    linkHover: '#f9a8d4',
    codeBackground: '#0c0609',
    codeText: '#fce7f3',
    blockquoteBorder: '#ec4899',
    blockquoteBackground: '#1d1218',
    tableHeaderBackground: '#24141d',
    tableRowHover: '#2e1825',
    headingAnchor: '#ec4899',
  },
}

export const darkPurpleTheme: ThemeConfig = {
  name: 'dark-purple',
  code: 'catppuccin-mocha',
  colors: {
    text: '#f1edff',
    textMuted: '#a59bd6',
    background: '#0e0c15',
    backgroundSecondary: '#161326',
    border: '#2a2550',
    link: '#a78bfa',
    linkHover: '#c4b5fd',
    codeBackground: '#08070f',
    codeText: '#f1edff',
    blockquoteBorder: '#8b5cf6',
    blockquoteBackground: '#161326',
    tableHeaderBackground: '#1c1835',
    tableRowHover: '#25204a',
    headingAnchor: '#a78bfa',
  },
}

export const githubTheme: ThemeConfig = {
  name: 'github',
  code: 'github-light',
  colors: {
    text: '#24292e',
    textMuted: '#586069',
    background: '#ffffff',
    backgroundSecondary: '#f6f8fa',
    border: '#e1e4e8',
    link: '#0366d6',
    linkHover: '#0255b3',
    codeBackground: '#f6f8fa',
    codeText: '#24292e',
    blockquoteBorder: '#dfe2e5',
    blockquoteBackground: 'transparent',
    tableHeaderBackground: '#f6f8fa',
    tableRowHover: '#f6f8fa',
    headingAnchor: '#bbb',
  },
}

export const draculaTheme: ThemeConfig = {
  name: 'dracula',
  code: 'dracula',
  colors: {
    text: '#f8f8f2',
    textMuted: '#9aa4c7',
    background: '#0f111a',
    backgroundSecondary: '#1a1d2b',
    border: '#44475a',
    link: '#8be9fd',
    linkHover: '#6ad7fb',
    codeBackground: '#1a1d2b',
    codeText: '#f8f8f2',
    blockquoteBorder: '#bd93f9',
    blockquoteBackground: '#1a1d2b',
    tableHeaderBackground: '#1a1d2b',
    tableRowHover: '#2a2e42',
    headingAnchor: '#6272a4',
  },
}
