import type { ThemeConfig } from '../core/types'

export const lightTheme: ThemeConfig = {
  name: 'light',
  code: 'github-light',
  colors: {
    text: '#1a1a1a',
    textMuted: '#6b7280',
    background: '#ffffff',
    backgroundSecondary: '#f9fafb',
    border: '#e5e7eb',
    link: '#2563eb',
    linkHover: '#1d4ed8',
    codeBackground: '#f3f4f6',
    codeText: '#1f2937',
    blockquoteBorder: '#d1d5db',
    blockquoteBackground: '#f9fafb',
    tableHeaderBackground: '#f3f4f6',
    tableRowHover: '#f9fafb',
    headingAnchor: '#9ca3af',
  },
}

export const lightGreenTheme: ThemeConfig = {
  name: 'light-green',
  code: 'vitesse-light',
  colors: {
    text: '#14532d',
    textMuted: '#4b7a5a',
    background: '#ffffff',
    backgroundSecondary: '#dcfce7',
    border: '#bbf7d0',
    link: '#16a34a',
    linkHover: '#15803d',
    codeBackground: '#dcfce7',
    codeText: '#14532d',
    blockquoteBorder: '#4ade80',
    blockquoteBackground: '#f0fdf4',
    tableHeaderBackground: '#dcfce7',
    tableRowHover: '#f0fdf4',
    headingAnchor: '#86efac',
  },
}

export const lightOrangeTheme: ThemeConfig = {
  name: 'light-orange',
  code: 'catppuccin-latte',
  colors: {
    text: '#7c2d12',
    textMuted: '#a07040',
    background: '#ffffff',
    backgroundSecondary: '#ffedd5',
    border: '#fed7aa',
    link: '#ea580c',
    linkHover: '#c2410c',
    codeBackground: '#ffedd5',
    codeText: '#7c2d12',
    blockquoteBorder: '#fb923c',
    blockquoteBackground: '#fff7ed',
    tableHeaderBackground: '#ffedd5',
    tableRowHover: '#fff7ed',
    headingAnchor: '#fdba74',
  },
}

export const lightPinkTheme: ThemeConfig = {
  name: 'light-pink',
  code: 'catppuccin-latte',
  colors: {
    text: '#881337',
    textMuted: '#9d4f72',
    background: '#ffffff',
    backgroundSecondary: '#ffe4e6',
    border: '#fecdd3',
    link: '#e11d48',
    linkHover: '#be123c',
    codeBackground: '#ffe4e6',
    codeText: '#881337',
    blockquoteBorder: '#fb7185',
    blockquoteBackground: '#fff1f2',
    tableHeaderBackground: '#ffe4e6',
    tableRowHover: '#fff1f2',
    headingAnchor: '#fda4af',
  },
}

export const lightPurpleTheme: ThemeConfig = {
  name: 'light-purple',
  code: 'vitesse-light',
  colors: {
    text: '#3b0764',
    textMuted: '#7e5baa',
    background: '#ffffff',
    backgroundSecondary: '#f3e8ff',
    border: '#e9d5ff',
    link: '#9333ea',
    linkHover: '#7e22ce',
    codeBackground: '#f3e8ff',
    codeText: '#3b0764',
    blockquoteBorder: '#c084fc',
    blockquoteBackground: '#faf5ff',
    tableHeaderBackground: '#f3e8ff',
    tableRowHover: '#faf5ff',
    headingAnchor: '#d8b4fe',
  },
}

export const darkTheme: ThemeConfig = {
  name: 'dark',
  code: 'one-dark-pro',
  colors: {
    text: '#d4d4d4',
    textMuted: '#858585',
    background: '#262626',
    backgroundSecondary: '#252526',
    border: '#3e3e42',
    link: '#4ec9b0',
    linkHover: '#9cdcfe',
    codeBackground: '#141414',
    codeText: '#d4d4d4',
    blockquoteBorder: '#569cd6',
    blockquoteBackground: '#252526',
    tableHeaderBackground: '#2d2d30',
    tableRowHover: '#2a2d2e',
    headingAnchor: '#6e6e6e',
  },
}

export const darkGreenTheme: ThemeConfig = {
  name: 'dark-green',
  code: 'vitesse-dark',
  colors: {
    text: '#e2f2e2',
    textMuted: '#6a9f6a',
    background: '#262626',
    backgroundSecondary: '#132013',
    border: '#1e3a1e',
    link: '#4ade80',
    linkHover: '#86efac',
    codeBackground: '#081408',
    codeText: '#d1fad1',
    blockquoteBorder: '#22c55e',
    blockquoteBackground: '#132013',
    tableHeaderBackground: '#162916',
    tableRowHover: '#1c361c',
    headingAnchor: '#4ade80',
  },
}

export const darkOrangeTheme: ThemeConfig = {
  name: 'dark-orange',
  code: 'one-dark-pro',
  colors: {
    text: '#fef0d8',
    textMuted: '#b07840',
    background: '#262626',
    backgroundSecondary: '#251500',
    border: '#3d2200',
    link: '#fb923c',
    linkHover: '#fdba74',
    codeBackground: '#120900',
    codeText: '#fef0d8',
    blockquoteBorder: '#f97316',
    blockquoteBackground: '#251500',
    tableHeaderBackground: '#2e1800',
    tableRowHover: '#3d2200',
    headingAnchor: '#d97706',
  },
}

export const darkPinkTheme: ThemeConfig = {
  name: 'dark-pink',
  code: 'catppuccin-mocha',
  colors: {
    text: '#fce7f3',
    textMuted: '#a05070',
    background: '#262626',
    backgroundSecondary: '#22101b',
    border: '#4a1a30',
    link: '#f472b6',
    linkHover: '#f9a8d4',
    codeBackground: '#130810',
    codeText: '#fce7f3',
    blockquoteBorder: '#ec4899',
    blockquoteBackground: '#22101b',
    tableHeaderBackground: '#2a1220',
    tableRowHover: '#3a1830',
    headingAnchor: '#db2777',
  },
}

export const darkPurpleTheme: ThemeConfig = {
  name: 'dark-purple',
  code: 'catppuccin-mocha',
  colors: {
    text: '#ede9f8',
    textMuted: '#8b7fc4',
    background: '#262626',
    backgroundSecondary: '#161228',
    border: '#2e2652',
    link: '#a78bfa',
    linkHover: '#c4b5fd',
    codeBackground: '#09070f',
    codeText: '#ede9f8',
    blockquoteBorder: '#7c3aed',
    blockquoteBackground: '#161228',
    tableHeaderBackground: '#1e1840',
    tableRowHover: '#28224f',
    headingAnchor: '#7c3aed',
  },
}

export const githubTheme: ThemeConfig = {
  name: 'github',
  code: 'github-light',
  colors: {
    text: '#24292e',
    textMuted: '#586069',
    background: '#ffffff',
    backgroundSecondary: '#f6f8fa',
    border: '#e1e4e8',
    link: '#0366d6',
    linkHover: '#0255b3',
    codeBackground: '#f6f8fa',
    codeText: '#24292e',
    blockquoteBorder: '#dfe2e5',
    blockquoteBackground: 'transparent',
    tableHeaderBackground: '#f6f8fa',
    tableRowHover: '#f6f8fa',
    headingAnchor: '#bbb',
  },
}

export const draculaTheme: ThemeConfig = {
  name: 'dracula',
  code: 'dracula',
  colors: {
    text: '#f8f8f2',
    textMuted: '#6272a4',
    background: '#262626',
    backgroundSecondary: '#21222c',
    border: '#44475a',
    link: '#8be9fd',
    linkHover: '#6ad7fb',
    codeBackground: '#21222c',
    codeText: '#f8f8f2',
    blockquoteBorder: '#6272a4',
    blockquoteBackground: '#21222c',
    tableHeaderBackground: '#21222c',
    tableRowHover: '#44475a',
    headingAnchor: '#6272a4',
  },
}
